name:                accelerate-parconc
version:             0.1.0.0
github:              "thalesmg/accelerate-parconc"
license:             GPL-3
author:              "Thales Macedo Garitezi"
maintainer:          "thalesmg@gmail.com"
copyright:           "2018 Thales Macedo Garitezi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/accelerate-parconc#readme>

dependencies:
  - base >= 4.7 && < 5
  - accelerate
  - accelerate-llvm
  - accelerate-llvm-native
  - accelerate-llvm-ptx
  - cuda
  - llvm-hs
  - llvm-hs-pure

library:
  source-dirs: src

executables:
  cpu: &padrao
    main: cpu.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - accelerate-parconc

  gpu:
    <<: *padrao
    main: gpu.hs
    cpp-options: -DUSE_GPU

benchmarks:
  bench: &padrao-bench
    main: dotp.hs
    source-dirs: bench
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - accelerate-parconc
      - criterion

  shortest-gpu:
    <<: *padrao-bench
    main: shortest.hs
    cpp-options:
      - -DUSE_GPU

  shortest-cpu:
    <<: *padrao-bench
    main: shortest.hs
